const busData = {
  data: [
    {
      id: 101,
      imgUrl: [
        "https://s3-ap-southeast-1.amazonaws.com/rb-plus/BI/APP/IDN/WM/25217/1685/FR/DL/OEfXFk.jpeg",
        "https://s3-ap-southeast-1.amazonaws.com/rb-plus/BI/APP/IDN/WM/25217/1685/GW/DL/nuMRJ0.jpeg",
        "https://s3-ap-southeast-1.amazonaws.com/rb-plus/BI/APP/IDN/WM/25217/1685/ST/DL/SZeq6X.jpeg",
      ],
      route: ["Bandung", "Jakarta"],
      busBrandImg:
        "https://unicorn.indorent.co.id/Content/userimage/unicorn_blue.png",
      destination: "Jakarta",
      departureTime: "08:00",
      seatsAvailable: 36,
      rating: 4.5,
      busType: "Economy",
      brandBus: "Unicorn Indorent",
      facilites: [
        "WiFi",
        "Air Conditioning",
        "Restroom",
        "Wheelchair Accessible",
        "USB Charging Ports",
      ],
      price: 100000,
    },
    {
      id: 102,
      imgUrl: ["gambar1.jpg", "gambar2.jpg", "gambar3.jpg"],
      route: ["Surabaya", "Malang"],
      busBrandImg: "https://www.sinarjayagroup.co.id/images/logo/logo-sj.png",
      destination: "Malang",
      departureTime: "09:30",
      seatsAvailable: 40,
      rating: 4,
      busType: "Economy",
      brandBus: "Sinar Jaya",
      facilites: [
        "WiFi",
        "Air Conditioning",
        "Restroom",
        "Wheelchair Accessible",
        "USB Charging Ports",
      ],
      price: 100000,
    },
    {
      id: 103,
      imgUrl: ["gambar1.jpg", "gambar2.jpg", "gambar3.jpg"],
      route: ["Yogyakarta", "Solo"],
      destination: "Solo",
      departureTime: "10:15",
      seatsAvailable: 45,
      brandBus: "PO Raya",
      rating: 4,
      busType: "Economy",
      facilites: [
        "WiFi",
        "Air Conditioning",
        "Restroom",
        "Wheelchair Accessible",
        "USB Charging Ports",
      ],
      price: 100000,
    },
    {
      id: 104,
      imgUrl: ["gambar1.jpg", "gambar2.jpg", "gambar3.jpg"],
      route: ["Medan", "Banda Aceh"],
      destination: "Banda Aceh",
      busBrandImg: "https://www.sinarjayagroup.co.id/images/logo/logo-sj.png",
      departureTime: "11:45",
      seatsAvailable: 60,
      brandBus: "Sinar Jaya",
      rating: 4,
      busType: "Economy",
      facilites: [
        "WiFi",
        "Air Conditioning",
        "Restroom",
        "Wheelchair Accessible",
        "USB Charging Ports",
      ],
      price: 100000,
    },
    {
      id: 105,
      imgUrl: ["gambar1.jpg", "gambar2.jpg", "gambar3.jpg"],
      route: ["Denpasar", "Ubud"],
      destination: "Ubud",
      busBrandImg: "https://www.sinarjayagroup.co.id/images/logo/logo-sj.png",
      departureTime: "13:00",
      seatsAvailable: 55,
      brandBus: "Sinar Jaya",
      rating: 4,
      busType: "Economy",
      facilites: [
        "WiFi",
        "Air Conditioning",
        "Restroom",
        "Wheelchair Accessible",
        "USB Charging Ports",
      ],
      price: 100000,
    },
  ],
};
export default busData;
